Added missing <optional> header (#1251)
I am getting this error in EndeavorOS/Arch Linux when running  cmake --build build

/home/vivek/Downloads/DigiDoc4-Client/client/Application.cpp:296:14: error: ‘optional’ in namespace ‘std’ does not name a template type
  296 |         std::optional<std::string> log;
      |              ^~~~~~~~
/home/vivek/Downloads/DigiDoc4-Client/client/Application.cpp:76:1: note: ‘std::optional’ is defined in header ‘<optional>’; did you forget to ‘#include <optional>’?
   75 | #include <QtWidgets/QToolTip>
  +++ |+#include <optional>
   76 | 


Adding  missing <optional> header in /DigiDoc4-Client/client/Application.cpp fixes this issue.