Include missing <QRegExp> to fix Qt6 build
```
.../client/Application.cpp:727:19: error: use of undeclared identifier 'QRegExp'
        if( env.indexOf( QRegExp("KDE_FULL_SESSION.*") ) != -1 )
                         ^
.../Application.cpp:738:24: error: use of undeclared identifier 'QRegExp'
        else if( env.indexOf( QRegExp("GNOME_DESKTOP_SESSION_ID.*") ) != -1 )
                              ^
2 errors generated.
```

No idea why this builds fine against Qt5, but Qt6 fails as per above.

Qt6 provides this header under Qt5Core5Compact.

Signed-off-by: Klemens Nanni <klemens@posteo.de>